version: '3.3'

services:

  app:
    build:
      context: .
    image: card_service
    ports:
      - "8000:8000"
    volumes:
      - ./cards:/usr/src/app
    env_file: .env
    command: >
      sh -c 'python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db
      - redis_broker

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/db
    env_file:
      .env
    ports:
      - "5432:5432"

  redis_broker:
    container_name: redis_broker
    image: redis:6.2-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A cards.celery worker -l info
    volumes:
      - ./cards/:/usr/src/app/
    env_file:
      .env
    depends_on:
      - redis_broker
volumes:
  db-data:
