# Generated by Django 4.1.4 on 2022-12-25 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20, verbose_name='Серия карты')),
                ('number', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_of_serving_datetime', models.DateTimeField(verbose_name='Дата окончания обслуживания')),
                ('balance', models.IntegerField(default=1000, verbose_name='Баланс')),
                ('status', models.CharField(choices=[('Activated', 'Активирована'), ('Unactivated', 'Не активирована'), ('Overdued', 'Просрочена')], default='Activated', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_use', models.DateTimeField(auto_now_add=True, verbose_name='Дата совершения платежа')),
                ('amount', models.IntegerField(verbose_name='Сумма платежа')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_service.card')),
            ],
        ),
    ]
